// <auto-generated />
namespace GestionDesCourses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Mariam2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Mariam2));
        
        string IMigrationMetadata.Id
        {
            get { return "201903041433312_Mariam2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
