// <auto-generated />
namespace GestionDesCourses.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MAJ_EF : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MAJ_EF));
        
        string IMigrationMetadata.Id
        {
            get { return "201902280952323_MAJ_EF"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
